# Generated by Django 4.1.3 on 2022-11-09 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_prov', models.CharField(max_length=2)),
                ('nama_prov', models.CharField(max_length=30)),
                ('kode_kabkot', models.CharField(max_length=4)),
                ('nama_kabkot', models.CharField(max_length=30)),
                ('kode_kec', models.CharField(max_length=6)),
                ('nama_kec', models.CharField(max_length=30)),
                ('kode_desa', models.CharField(max_length=10)),
                ('nama_desa', models.CharField(max_length=30)),
                ('dasar_hukum', models.CharField(max_length=30)),
                ('status_data', models.CharField(choices=[('updated', 'updated'), ('depreciated', 'depreciated')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alamat',
                'verbose_name_plural': 'Alamat',
            },
        ),
        migrations.CreateModel(
            name='KodePos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=5)),
                ('dasar_hukum', models.CharField(max_length=30)),
                ('status_data', models.CharField(choices=[('updated', 'updated'), ('depreciated', 'depreciated')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kode Pos',
                'verbose_name_plural': 'Kode Pos',
            },
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'verbose_name': 'Testing Data', 'verbose_name_plural': 'Testing Data'},
        ),
    ]
