# Generated by Django 4.1.3 on 2022-11-10 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_alamat_kodepos_alter_testing_options_delete_provinsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBJI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_gol_pokok', models.PositiveSmallIntegerField(unique=True, verbose_name='Kode Golongan Pokok')),
                ('golongan_pokok', models.CharField(max_length=50, verbose_name='Nama Golongan Pokok')),
                ('kode_subgol_pokok', models.PositiveSmallIntegerField(unique=True, verbose_name='Kode Sub-Golongan Pokok')),
                ('subgolongan_pokok', models.CharField(max_length=50, verbose_name='Nama Sub-Golongan Pokok')),
                ('kode_gol', models.PositiveSmallIntegerField(unique=True, verbose_name='Kode Golongan')),
                ('golongan', models.CharField(max_length=50, verbose_name='Nama Golongan')),
                ('kode_subgol', models.PositiveSmallIntegerField(unique=True, verbose_name='Kode Sub-Golongan')),
                ('subgolongan', models.CharField(max_length=50, verbose_name='Nama Sub-Golongan')),
                ('kode_jabatan', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kode Jabatan')),
                ('jabatan', models.CharField(max_length=50, verbose_name='Nama Jabatan')),
                ('dasar_hukum', models.CharField(max_length=30)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Depreciated', 'Depreciated')], max_length=11, verbose_name='Status Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klasifikasi Baku Jabatan',
                'verbose_name_plural': 'Klasifikasi Baku Jabatan',
            },
        ),
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.PositiveBigIntegerField(unique=True, verbose_name='Nomor Induk Kependudukan')),
                ('nama_lengkap', models.CharField(help_text='Nama sesuai KTP, tidak ditambahkan gelar.', max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=9)),
                ('tempat_lahir', models.CharField(max_length=30)),
                ('tanggal_lahir', models.DateField()),
                ('status_kawin', models.CharField(choices=[('Belum Kawin', 'Belum Kawin'), ('Kawin', 'Kawin'), ('Cerai Hidup', 'Cerai Hidup'), ('Cerai Mati', 'Cerai Mati')], max_length=11)),
                ('rt', models.PositiveSmallIntegerField(verbose_name='RT')),
                ('rw', models.PositiveSmallIntegerField(verbose_name='RW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orang',
                'verbose_name_plural': 'Orang',
            },
        ),
        migrations.CreateModel(
            name='Profesi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_kbji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kbji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesi',
                'verbose_name_plural': 'Profesi',
            },
        ),
        migrations.AlterField(
            model_name='alamat',
            name='dasar_hukum',
            field=models.CharField(max_length=30, verbose_name='Dasar Hukum'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='kode_desa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode Desa/Kelurahan'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='kode_kabkot',
            field=models.CharField(max_length=4, unique=True, verbose_name='Kode Kabupaten/Kota'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='kode_kec',
            field=models.CharField(max_length=6, unique=True, verbose_name='Kode Kecamatan'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='kode_prov',
            field=models.CharField(max_length=2, unique=True, verbose_name='Kode Provinsi'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='nama_desa',
            field=models.CharField(help_text="Tuliskan nama desa tanpa imbuhan 'Desa', 'Ds.' dsb. Untuk nama kelurahan, gunakan imbuhan 'Kel.'. Tulisan akan otomatis terkonversi menjadi huruf kapital.", max_length=30, verbose_name='Nama Desa/Kelurahan'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='nama_kabkot',
            field=models.CharField(help_text="Tuliskan nama kabupaten tanpa imbuhan 'Kabupaten', 'Kab.' dsb. Untuk nama kota, gunakan imbuhan 'Kota'. Tulisan akan otomatis terkonversi menjadi huruf kapital.", max_length=30, verbose_name='Nama Kabupaten/Kota'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='nama_kec',
            field=models.CharField(help_text="Tuliskan nama kecamatan tanpa imbuhan 'Kecamatan', 'Kec.' dsb. Tulisan akan otomatis terkonversi menjadi huruf kapital.", max_length=30, verbose_name='Nama Kecamatan'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='nama_prov',
            field=models.CharField(help_text="Tuliskan nama provinsi tanpa imbuhan 'Provinsi', 'Prov.' dsb. Tulisan akan otomatis terkonversi menjadi huruf kapital.", max_length=30, verbose_name='Nama Provinsi'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='status_data',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Depreciated', 'Depreciated')], max_length=11, verbose_name='Status Data'),
        ),
        migrations.AlterField(
            model_name='kodepos',
            name='dasar_hukum',
            field=models.CharField(max_length=30, verbose_name='Dasar Hukum'),
        ),
        migrations.AlterField(
            model_name='kodepos',
            name='status_data',
            field=models.CharField(choices=[('Updated', 'Updated'), ('Depreciated', 'Depreciated')], max_length=11, verbose_name='Status Data'),
        ),
        migrations.DeleteModel(
            name='Provinsi',
        ),
        migrations.AddField(
            model_name='orang',
            name='alamat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat'),
        ),
        migrations.AddField(
            model_name='orang',
            name='profesi',
            field=models.ManyToManyField(to='data.profesi'),
        ),
        migrations.AddField(
            model_name='orang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
