# Generated by Django 4.1.3 on 2022-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_kbji_orang_profesi_alter_alamat_dasar_hukum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alamat',
            name='kode_kabkot',
            field=models.CharField(max_length=4, verbose_name='Kode Kabupaten/Kota'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='kode_kec',
            field=models.CharField(max_length=6, verbose_name='Kode Kecamatan'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='kode_prov',
            field=models.CharField(max_length=2, verbose_name='Kode Provinsi'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='golongan',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=50, verbose_name='Nama Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='golongan_pokok',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=50, verbose_name='Nama Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='jabatan',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=50, verbose_name='Nama Jabatan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_gol',
            field=models.PositiveSmallIntegerField(verbose_name='Kode Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_gol_pokok',
            field=models.PositiveSmallIntegerField(verbose_name='Kode Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_jabatan',
            field=models.DecimalField(decimal_places=2, max_digits=6, unique=True, verbose_name='Kode Jabatan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_subgol',
            field=models.PositiveSmallIntegerField(verbose_name='Kode Sub-Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_subgol_pokok',
            field=models.PositiveSmallIntegerField(verbose_name='Kode Sub-Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='subgolongan',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=50, verbose_name='Nama Sub-Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='subgolongan_pokok',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=50, verbose_name='Nama Sub-Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='orang',
            name='tempat_lahir',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=30),
        ),
    ]
