# Generated by Django 4.1.3 on 2022-11-11 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0004_alter_alamat_kode_kabkot_alter_alamat_kode_kec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nkk', models.PositiveBigIntegerField(unique=True, verbose_name='Nomor Kartu Kependudukan')),
                ('rt', models.PositiveSmallIntegerField(verbose_name='RT')),
                ('rw', models.PositiveSmallIntegerField(verbose_name='RW')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.alamat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keluarga',
                'verbose_name_plural': 'Keluarga',
            },
        ),
        migrations.CreateModel(
            name='AnggotaKeluarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_anggota', models.CharField(choices=[('Kepala', 'Kepala'), ('Anggota', 'Anggota')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keluarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.keluarga')),
                ('orang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.orang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anggota Keluarga',
                'verbose_name_plural': 'Anggota Keluarga',
            },
        ),
    ]
