# Generated by Django 4.1.3 on 2022-11-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_keluarga_anggotakeluarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbji',
            name='golongan',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=100, verbose_name='Nama Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='golongan_pokok',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=100, verbose_name='Nama Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='jabatan',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=100, verbose_name='Nama Jabatan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_gol',
            field=models.CharField(max_length=3, verbose_name='Kode Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_gol_pokok',
            field=models.CharField(max_length=1, verbose_name='Kode Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_subgol',
            field=models.CharField(max_length=4, verbose_name='Kode Sub-Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='kode_subgol_pokok',
            field=models.CharField(max_length=2, verbose_name='Kode Sub-Golongan Pokok'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='subgolongan',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=100, verbose_name='Nama Sub-Golongan'),
        ),
        migrations.AlterField(
            model_name='kbji',
            name='subgolongan_pokok',
            field=models.CharField(help_text='Tulisan akan otomatis terkonversi menjadi huruf kapital.', max_length=100, verbose_name='Nama Sub-Golongan Pokok'),
        ),
    ]
