# Generated by Django 4.1.3 on 2022-11-18 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_alter_kbji_golongan_alter_kbji_golongan_pokok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbji',
            name='dasar_hukum',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='SITC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_section', models.CharField(max_length=1)),
                ('kode_division', models.CharField(max_length=2)),
                ('kode_group', models.CharField(max_length=3)),
                ('kode_subgroup', models.CharField(max_length=5)),
                ('kode_heading', models.CharField(max_length=6)),
                ('deskripsi_section', models.TextField()),
                ('deskripsi_division', models.TextField()),
                ('deskripsi_group', models.TextField()),
                ('deskripsi_subgroup', models.TextField()),
                ('deskripsi_heading', models.TextField()),
                ('dasar_hukum', models.CharField(max_length=120)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Depreciated', 'Depreciated')], max_length=11, verbose_name='Status Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klasifikasi Baku Komoditas',
                'verbose_name_plural': 'Klasifikasi Baku Komoditas',
            },
        ),
    ]
