# Generated by Django 4.1.3 on 2022-11-23 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0008_spesies'),
    ]

    operations = [
        migrations.CreateModel(
            name='IUCN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kategori', models.CharField(choices=[('NE', 'Not Evaluated'), ('DD', 'Data Deficient'), ('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], max_length=2)),
                ('tanggal_asesmen', models.DateField()),
                ('referensi_asesmen', models.TextField()),
                ('habitat_asal', models.CharField(max_length=50)),
                ('lokasi_geografis', models.TextField(help_text='Saat ini tolong diisikan dengan koordinat Well-known Text (WKT) Geografis WGS84. Ke depan akan diganti dengan fitur digitasi spasial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spesies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.spesies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IUCN Red List',
                'verbose_name_plural': 'IUCN Red List',
            },
        ),
    ]
