# Generated by Django 4.1.3 on 2022-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_iucn'),
    ]

    operations = [
        migrations.AddField(
            model_name='spesies',
            name='nama_indonesia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='spesies',
            name='nama_inggris',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='nama_desa',
            field=models.CharField(help_text="Tuliskan nama desa tanpa imbuhan 'Desa', 'Ds.' dsb. Untuk nama kelurahan, gunakan imbuhan 'Kel.'. Tulisan akan otomatis terkonversi menjadi huruf kapital.", max_length=40, verbose_name='Nama Desa/Kelurahan'),
        ),
        migrations.AlterField(
            model_name='alamat',
            name='nama_kec',
            field=models.CharField(help_text="Tuliskan nama kecamatan tanpa imbuhan 'Kecamatan', 'Kec.' dsb. Tulisan akan otomatis terkonversi menjadi huruf kapital.", max_length=40, verbose_name='Nama Kecamatan'),
        ),
        migrations.AlterField(
            model_name='iucn',
            name='lokasi_geografis',
            field=models.TextField(blank=True, help_text='Saat ini tolong diisikan dengan koordinat Well-known Text (WKT) Geografis WGS84. Ke depan akan diganti dengan fitur digitasi spasial'),
        ),
    ]
