# Generated by Django 4.1.3 on 2022-12-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0011_isced_attainment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iucn',
            name='habitat_asal',
        ),
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_singkat', models.CharField(max_length=100)),
                ('nama_resmi', models.CharField(max_length=100)),
                ('region_pbb', models.CharField(choices=[('Africa', 'Africa'), ('Americas', 'Americas'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Oceania', 'Oceania')], max_length=15, verbose_name='Region PBB')),
                ('subregion', models.CharField(choices=[('Caribbean', 'Caribbean'), ('Central America', 'Central America'), ('Central Asia', 'Central Asia'), ('Eastern Africa', 'Eastern Africa'), ('Eastern Asia', 'Eastern Asia'), ('Eastern Europe', 'Eastern Europe'), ('Melanesia', 'Melanesia'), ('Micronesia', 'Micronesia'), ('Middle Africa', 'Middle Africa'), ('Northern Africa', 'Northern Africa'), ('Northern America', 'Northern America'), ('Northern Europe', 'Northern Europe'), ('Polynesia', 'Polynesia'), ('Seven seas (open ocean)', 'Seven seas (open ocean)'), ('South America', 'South America'), ('South-Eastern Asia', 'South-Eastern Asia'), ('Southern Africa', 'Southern Africa'), ('Southern Asia', 'Southern Asia'), ('Southern Europe', 'Southern Europe'), ('Western Africa', 'Western Africa'), ('Western Asia', 'Western Asia'), ('Western Europe', 'Western Europe')], max_length=30)),
                ('region_wb', models.CharField(choices=[('Antarctica', 'Antarctica'), ('Australia and New Zealand', 'Australia and New Zealand'), ('Antarctica', 'Antarctica'), ('East Asia & Pacific', 'East Asia & Pacific'), ('Europe & Central Asia', 'Europe & Central Asia'), ('Latin America & Caribbean', 'Latin America & Caribbean'), ('Middle East & North Africa', 'Middle East & North Africa'), ('North America', 'North America'), ('South Asia', 'South Asia'), ('Sub-Saharan Africa', 'Sub-Saharan Africa')], max_length=30, verbose_name='Region World Bank')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dasar_hukum', models.CharField(max_length=120)),
                ('status_data', models.CharField(choices=[('Updated', 'Updated'), ('Depreciated', 'Depreciated')], max_length=11, verbose_name='Status Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orang',
                'verbose_name_plural': 'Orang',
            },
        ),
        migrations.AddField(
            model_name='iucn',
            name='habitat_asal',
            field=models.ManyToManyField(to='data.negara'),
        ),
    ]
